### ISSUE TITLE
consumption emissions (MtCO2eq)

### ISSUE THREAD

**Issue by eabjmyy222** [CIRAIG/OpenIO-Canada#20]
Hi, I'm currently studying EEIO analysis method and found your JCR manuscript quite informative. I am curious how you calculated the results presented in the following statement: "In 2017, Canada's consumption was responsible for the release of 692 MtCO2eq." Specifically, is this figure derived by summing all the values in Table E (the total emissions table)? Thanks.

**Comment by MaximeAgez** [comment]
Hi, not sure where I made that statement but the numbers still match with the current openIO-Canada version. You would obtain this figure, not by summing values in the E table, because this table contains all elementary flows (aka environmental stressors) so not just GHGs. Furthermore, they are quantified in kgs of elemnetary flows, and you cannot sum kg of CO2 with kg of CH4. You first need to convert them to a common unit, the kgCO2eq. That's the operation that is done in the C matrix, based on the IPCC methodology. So to get the 692MtCO2eq figure (or at least close to it depending on the version and year) you would take a look at the D table, which comes from the operation D = C . S . (I-A)^-1 . Y + C . FY
Or using the E matrix that you mention, it is simply D = C . E

**Comment by eabjmyy222** [comment]
Thank you for your quick response and clarification. To confirm my understanding, for instance, using your demo code, to calculate consumption-based GHG emissions based on the "D" table, I would sum up all the values in the "climate change, long term (kg CO2eq)" row and subtract the values for "International exports." Please let me know if I understand it correctly. Thanks.

<img width="526" alt="Screenshot 2023-10-05 131742" src="https://github.com/CIRAIG/OpenIO-Canada/assets/77300290/b63774fe-87f2-47a3-ad61-afdea847ee88">

**Comment by MaximeAgez** [comment]
Correct. We exclude international exports if you want to follow a consumption-based accounting approach. 
However, the Climate change, long term indicator actually represents the GTP100 indicator. The GWP100 indicator (more commonly used) is actually the row Climate change, short term. So you would need to sum that row instead.

**Comment by eabjmyy222** [comment]
Thank you so much! This helps a lot.

**Comment by eabjmyy222** [comment]
Hi again. I'm curious about the GWP100 value of 36 for CH4 in Table C. I've come across values like 21, 23, and 25 in the IPCC report, but I couldn't locate 36. Could you kindly provide some clarification? Thank you in advance.

**Comment by MaximeAgez** [comment]
Hi! So the 36kgCO2eq value is coming from the IMPACT World+ life cycle impact assessment method. The latter is based on the IPCC AR5 using feedback loops (i.e., further degradation of methane into CO2 meaning it has an additional impact). So if you check the table 8.7 from the 8th CHapter of the AR5 you would see the value 34kgCO2eq for methane with feedback loop. I believe the IW+ also including some other methodological aspect making it to 36kgCO2eq instead of 34kgCO2eq.

Since this year, the AR6 came out, and turns out the IPCC now provides only the methane value including the feedback loops. In the AR6 the current value for methane is 30kgCO2eq (Table 7.15 of the chapter 7 of the AR6)

So in the end, it's just that I haven't yet updated the characterization factors to the AR6 report values. I will probably do that with the next version alongside the data for the 2020 year.
In the meantime, you can simply edit the value in the C matrix to modify it to whichever value you want to apply.

**Comment by eabjmyy222** [comment]
Thanks. May I ask why you did not use the value 25 for methane in your study? I noticed that 25 is used by Physical flow accounts. Are there specific requirements regarding the adoption of different GWP values (i.e., for CH4)? I see there are various values out there used by academic manuscript and government reports, but does know quite understand why.

**Comment by MaximeAgez** [comment]
Last time I checked (maybe two years ago) physical flow accounts were still using the IPCC2007 characterization factors. And at that time there was already an update with the IPCC2013 factors. That is why the values from physical flow accounts were not used directly.

**Comment by eabjmyy222** [comment]
I see. Thank you so much for your prompt reply.
