### ISSUE TITLE
Consumption Approach Validation

### ISSUE THREAD

**Issue by PaaloMoreno** [CIRAIG/OpenIO-Canada#29]
I am currently conducting validation using version 2.9. While I can easily obtain the production-based approach value, I am encountering a discrepancy with the consumption-based approach value. My process involves extracting the D matrix and excluding international exports, including exports and re-exports, then summing all remaining values to obtain the short-term CO2 emissions, which amounts to 718 Mton. I'm uncertain if I should exclude additional values and how to interpret the re-exports value. Any insights would be greatly appreciated. Thank you.

**Comment by MaximeAgez** [comment]
To get the consumption approach value you simply take the D matrix and you exclude all "International exports" columns. There should be 13 of them, one for each province. 
Note that if you try to validate with the numbers I put in the validations.md file, you should not endogenize capitals, otherwise you will necessarily get a different value.

**Comment by PaaloMoreno** [comment]
Thank you so much. I endogenize capitals.
