### ISSUE TITLE
Zero emission sectors

### ISSUE THREAD

**Issue by PaaloMoreno** [CIRAIG/OpenIO-Canada#30]
I'm currently using the model to calculate the greenhouse gas emissions of a Quebec-based company. Within the model, some sectors are recorded as having zero emissions. Notably, I find that some sectors in the province of Québec have no associated emissions. I am puzzled by the allocation of employee remuneration to an Input-Output (IO) sector. While the most suitable option from the available finance sectors appears to be 5221A0, 'Banking and other depository credit intermediation services - explicit charges,' it has no emissions associated. Therefore, I'm considering sector 522300, 'Other services related to credit intermediation.' I'm curious to know from your experience if this sector is appropriate for this purpose

**Comment by MaximeAgez** [comment]
The employee wages are represented in the value added of each sector (look at matrices R for normalized added value or W for the absolute version). There is no emissions associated with the a company providing wages to their employee. That is because we consider that whatever happens next with this money is the responsibility of the employee. 
Nevertheless, if you still wish to account for this, I'd suggest simply normalizing the final demand by households /$ and then using this distribution to scale the wages paid by the company.

**Comment by PaaloMoreno** [comment]
Thank you so much for your explanation. Based on this information, I'm curious if I should include in my model the social charges that the company pays for its employees, such as Trusteed pension fund services and Health and accident insurance services. Additionally, I'm interested to know if I should include the amortization of debts. Clarification on these aspects would be greatly appreciated.

**Comment by MaximeAgez** [comment]
I'm not sure for all these things, but the general idea is that if the company pays a service, then it is part of their impact, but if they pay things directly to the employees, then it should not be. So for example, even if the employee gets insurance through its company, the company is actually paying an insurance company to deal with that ultimately. So the amount that the company pays to the insurance company for its employees should be included.

**Comment by PaaloMoreno** [comment]
Thank you so much for your response
